version: '3.9'

services:
  server:
    build: .
    ports: 
      - "8080:8080"
  db:
    image: 'postgres'
    volumes:
      - mydata2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data1:/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - server
      - db
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - server
      - db
      - prometheus
volumes:
  mydata2:
  prometheus-data1:
  grafana-data:
