version: '3.9'

services:
  server:
    build: .
    ports: 
      - "8080:8080"
  db:
    image: 'postgres'
    ports:
      - '4444:5432'
    volumes:
      - mydata2:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus/data
    ports:
      - '9090:9090'
    depends_on:
      - server
      - db

volumes:
  mydata2:
  prometheus_data:
